- name: install PyMySQL and cryptography 
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL
  
- name: installing maven 
  ansible.builtin.dnf:
    name: maven
    state: installed 

- name: create user for roboshop project 
  ansible.builtin.user:
    name: roboshop
    state: present
    comment: "roboshop system user"
    home: /app
    shell: /bin/bash

- name: create app directory 
  ansible.builtin.file:
    state: directory
    path: /app

- name: download catalogue content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
    dest: /app
    remote_src: yes

- name: install maven dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: copy shipping service file
  ansible.builtin.template:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service

- name:  daemon realod , enabled and start the service 
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: shipping
    state: started
    enabled: true

- name: install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Load the schema into database
  community.mysql.mysql_db:
    name: all
    login_host: "{{ MYSQL_HOST }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PWD }}"
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name:  daemon realod , enabled and start the service 
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: shipping
    state: restarted

